### ISSUE TITLE
Explicitly identify ISO8601 as the date-time format for DPN

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/DPN-REST-Wiki#13]
Reference the ISO8601 standard in
- https://github.com/dpn-admin/dpn-rest-spec/blob/master/Standards.md#dpn-format-date-time

**Comment by dazza-codes** [comment]
For example:
- https://www.w3.org/TR/NOTE-datetime
- http://www.iso.org/iso/home/standards/iso8601.htm

**Comment by Pcolar** [comment]
Updated in https://github.com/dpn-admin/dpn-rest-spec/pull/14
