### ISSUE TITLE
swagger is a JSON spec - create `dist/swagger.json` file

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/DPN-REST-Wiki#5]
After reading swagger-api/swagger-ui#595, it's clear that we should have a `dist/swagger.json` file in this project.

**Comment by malakai97** [comment]
> After reading swagger-api/swagger-ui#595, it's clear that we should have a dist/swagger.json file in the dpn-rest-spec:api-v2 project. When that is available, the symlinks for it in this project can be updated to use it.

Reading the entirety of https://github.com/swagger-api/swagger-ui/issues/595 yields https://github.com/swagger-api/swagger-js/pull/415, indicating that swagger-ui supports loading directly from yaml.  As far as I can tell with the available information, this need does not exist.

**Comment by dazza-codes** [comment]
I prefer to use a `dist/swagger.json` file - problem solved in #8 so there are no additional problems elsewhere to support swagger-ui in dpn-server.  Minimal effort to solve that problem - done - so long as we merge #8.
