### ISSUE TITLE
Update URLs in package.json

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/DPN-REST-Wiki#6]
Update the URLs in https://github.com/dpn-admin/dpn-rest-spec/blob/api-v2/package.json, i.e.
replace "url": "git://github.com/dpn-admin/DPN-REST-Wiki.git"
with "url": "git://github.com/dpn-admin/dpn-rest-spec.git"

**Comment by malakai97** [comment]
fixed in merge
